#!/bin/bash

CHANGED_FILES=$(git diff --cached --name-status | awk '$1 != "R" { print $2 }')
ROOT=$(dirname $0)

cd $ROOT/../../

function failCommit() {
    echo ''
    echo -e '\033[31mUnable to commit: '$1'\033[39m'
    exit 1
}

printf 'Checking Content'