#!/bin/bash

CHANGED_FILES=$(git diff --cached --name-status | awk '$1 != "R" { print $2 }')
ROOT=$(dirname $0)

cd $ROOT/../../

function failCommit() {
    echo ''
    echo -e '\033[31mUnable to commit: '$1'\033[39m'
    exit 1
}

printf 'Checking Content'
content_errors=0
while IFS= read -r -d $'\0' file; do
    result=$(grep '_test\.[a-zA-Z0-9_]*(' $file 2>&1)
    if [[ $result ]]; then
        echo ''
        echo '----------------------------------------'
        echo $file 'includes disallowed content:'
        echo $result
        echo '----------------------------------------'
        content_errors=$(($content_errors+1))
    else
        printf '.'
    fi
done < <(find . -name '*[^test].js' -print0)
if [[ $content_errors -gt 0 ]]; then
    failCommit "$content_errors Content Errors"
fi
echo ''